# Generated by Django 3.0.4 on 2020-03-23 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidtoken',
            name='access_token',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='plaidtoken',
            unique_together={('access_token', 'user')},
        ),
        migrations.RemoveField(
            model_name='plaidtoken',
            name='public_token',
        ),
    ]
